spring:
  application:
    name: Aquariux
  datasource:
    url: jdbc:h2:file:./aquariux.db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: aquariux
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      # http://localhost:8080/aquariux
      path: /aquariux
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true